### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by ayame113** [ayame113/socket-graph#5]
- [x] implements server side
  - [x] add server (first path)
  - [x] add router
  - [x] add swc to transpile TypeScript for browser
  - [x] DB access
  - [x] api implement
  - [x] add test
- [x] implements client side
- [ ] add PWA
- [x] add document
